server:
 port: 8080
 servlet:
   context-path: /techJobs

spring:
 config:
   import: optional:file:.env[.properties]
 datasource:
   url: "jdbc:mysql://localhost:3306/techjobdb"
   username: ${DB_USERNAME}
   password: ${DB_PASSWORD}
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
 servlet:
   multipart:
     max-file-size: 10MB
     max-request-size: 10MB
     enabled: true
 mail:
   host: smtp.gmail.com
   port: 587
   username: lehuuhau1231@gmail.com
   password: ${email-app-password}
   properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true
 data:
   redis:
     host: localhost
     port: 6379
 cache:
   type: redis
   redis:
     time-to-live: 20m 
# ai:
#   vertex:
#     ai:
#       gemini:
#         project-id: techjob-471215
#         location: us-central1
#         chat:
#           model: text-bison-001
#       embedding:
#         project-id: techjob-471215
#         location: us-central1
#         text:
#           options:
#             model: text-embedding-004
 ai:
   openai:
     base-url: http://127.0.0.1:1234
     api-key: test
     chat:
       options:
         model: google/gemma-4-e2b
     embedding:
       options:
         model: text-embedding-nomic-embed-text-v1.5

jwt:
 signerKey: ${signerKey}

cloudinary:
 cloud-name: ${cloud-name}
 api-key: ${cloud-api-key}
 api-secret: ${cloud-api-secret}
 secure: true

vnpay:
 version: "2.1.0"
 TmnCode: ${tmn-code}
 HashSecret: ${hash-secret}
 payUrl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
 returnUrl: ${returnUrl}
 ipnUrl: ${ipnUrl}
 orderType: "billpayment"
 locale: "vn"

address:
 provincesUrl: ${provincesUrl}
 districtsUrl: ${districtsUrl}

gemini:
 api:
   key: ${gemini-api-key}

embedding:
 type: "FLOAT32"
 dimension: 768
 distance-metric: "COSINE"
 model: "gemini-embedding-001"
