server:
  port: 8080
  servlet:
    context-path: /techJobs

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/techjobdb"
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lehuuhau1231@gmail.com
    password: ${email-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379



jwt:
  signerKey: ${signerKey}

cloudinary:
  cloud-name: ${cloud-name}
  api-key: ${cloud-api-key}
  api-secret: ${cloud-api-secret}
  secure: true

vnpay:
  version: "2.1.0"
  TmnCode: ${tmn-code}
  HashSecret: ${hash-secret}
  payUrl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  returnUrl: ${returnUrl}
  ipnUrl: ${ipnUrl}
  orderType: "billpayment"
  locale: "vn"

address:
  provincesUrl: ${provincesUrl}
  districtsUrl: ${districtsUrl}

gemini:
  api:
    key: ${gemini-api-key}

