server:
  port: 8080
  servlet:
    context-path: /techJobs

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/techjobdb"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "KMPH22iU4IExFBhtdQhyZoCn2JRkZ/WJeuu26VMZsH5SXXCfOxAVQwDwrDxHov1o"
