server:
  port: 8080
  servlet:
    context-path: /techJobs

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/techjobdb"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

jwt:
  signerKey: "KMPH22iU4IExFBhtdQhyZoCn2JRkZ/WJeuu26VMZsH5SXXCfOxAVQwDwrDxHov1o"

cloudinary:
  cloud-name: "dndsrbf9s"
  api-key: "932944391659178"
  api-secret: "_UlDjHd_T5WxNV0iZMMN9tGJuy0"
  secure: true

address:
  api-province: "https://tailieu365.com/api/address/province?mode=2"
  api-district: "https://tailieu365.com/api/address/district"
